const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {JSDOM}=require('jsdom'),{MessageChannel}=require('node:worker_threads');
const renderer=path.resolve(__dirname,'../src/renderer'),read=file=>fs.readFileSync(path.join(renderer,'services',file),'utf8');
function setup(t,modules){const dom=new JSDOM('<!doctype html><html><body></body></html>',{runScripts:'outside-only',url:'http://localhost/'});t.after(()=>dom.window.close());for(const file of modules)dom.window.eval(read(file));return dom.window;}
const presentation={pluginId:'test-plugin',pluginName:'Test',tool:'run',card:{version:1,title:'<img onerror=alert(1)>',description:'Actual snapshot',fields:[{label:'Name',value:'<script>x</script>'}],table:{columns:['A'],rows:[['<svg onload=x>']]}}};
test('plugin cards restore identical data with no HTML execution or duplicate card; no plugin code required',t=>{
 const w=setup(t,['PluginCards.js']);const host=w.document.createElement('div');host.innerHTML='<div class="tool-body"><pre>raw output</pre></div>';w.document.body.append(host);
 w.IexaPluginCards.updateTool(host,{pluginUI:presentation});const before=host.innerHTML;w.IexaPluginCards.updateTool(host,JSON.parse(JSON.stringify({pluginUI:presentation})));assert.equal(host.innerHTML,before);assert.equal(host.querySelectorAll('.plugin-result-card').length,1);assert.equal(host.querySelector('img,svg,script'),null);assert.match(host.textContent,/<script>x<\/script>/);assert.match(host.textContent,/raw output/);
 let event;w.addEventListener('iexa:open-plugin',e=>event=e.detail);host.querySelector('button').click();assert.equal(event.id,'test-plugin');w.IexaPluginCards.updateTool(host,{success:false});assert.equal(host.querySelector('.plugin-result-card'),null);
});
test('schema form submits typed values to real route contract and displays host card',async t=>{
 const w=setup(t,['PluginCards.js','PluginWorkspace.js']);let payload;w.fetch=async(url,init)=>{payload={url,args:JSON.parse(init.body).arguments};return{ok:true,json:async()=>({result:{success:true,output:'raw',pluginUI:presentation}})};};
 const form=w.IexaPluginWorkspace.createToolForm({id:'test-plugin'},{name:'run',description:'Run tool',parameters:{text:{type:'string'},count:{type:'integer'},enabled:{type:'boolean'},choice:{type:'string',enumValues:['a','b']}},required:['text','count']});w.document.body.append(form);form.elements.text.value='hello';form.elements.count.value='7';form.elements.enabled.value='false';form.elements.choice.value='b';form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.equal(payload.url,'/api/plugins/test-plugin/invoke');assert.deepEqual(payload.args,{text:'hello',count:7,enabled:false,choice:'b'});assert.equal(form.querySelector('.plugin-form-status').textContent,'已完成');assert.ok(form.querySelector('.plugin-result-card'));form.dispose();
});
test('schema form disposal aborts outstanding host fetch and suppresses detached result',async t=>{
 const w=setup(t,['PluginWorkspace.js']);let signal;w.fetch=(_,init)=>new Promise((resolve,reject)=>{signal=init.signal;signal.addEventListener('abort',()=>reject(new Error('abort')));});const form=w.IexaPluginWorkspace.createToolForm({id:'test-plugin'},{name:'run'});form.dispatchEvent(new w.Event('submit'));assert.equal(signal.aborted,false);form.dispose();await new Promise(r=>setImmediate(r));assert.equal(signal.aborted,true);assert.equal(form.querySelector('.plugin-form-output').textContent,'');
});
test('revocable bridge scopes requests to owning plugin, handles legacy, version, cancellation and theme',async t=>{
 const w=setup(t,[]);w.MessageChannel=MessageChannel;w.eval(read('PluginBridge.js'));let client;const frame={contentWindow:{postMessage(data,origin,ports){assert.equal(data.version,2);client=ports[0];}}};const requests=[];w.fetch=async(url,init)=>{requests.push({url,init});return{ok:true,json:async()=>({result:{success:true,output:'ok'}})};};const dispose=w.IexaPluginBridge.connect(frame,'owner');t.after(()=>{dispose();client.close();});
 const receive=()=>new Promise(resolve=>client.once('message',resolve));let response=receive();client.postMessage({type:'iexa-plugin-request',version:2,requestId:'one',method:'tool.invoke',params:{pluginId:'victim',tool:'run'}});assert.equal((await response).result.output,'ok');assert.equal(requests[0].url,'/api/plugins/owner/invoke');
 response=receive();client.postMessage({type:'iexa-plugin-call',requestId:'legacy',tool:'run'});assert.equal((await response).type,'iexa-plugin-result');
 response=receive();client.postMessage({type:'iexa-plugin-request',version:2,requestId:'unknown',method:'eval'});assert.match((await response).error,/未知/);
 response=receive();w.document.documentElement.dataset.theme='light';assert.equal((await response).value.theme,'light');
 let aborted=false;w.fetch=(_,init)=>new Promise((resolve,reject)=>init.signal.addEventListener('abort',()=>{aborted=true;reject(new Error('aborted'));}));client.postMessage({type:'iexa-plugin-request',version:2,requestId:'cancel',method:'tool.invoke',params:{tool:'run'}});await new Promise(r=>setTimeout(r,10));response=receive();client.postMessage({type:'iexa-plugin-cancel',requestId:'cancel'});assert.match((await response).error,/取消/);assert.equal(aborted,true);
 dispose();assert.equal(frame._iexaPluginDispose,undefined);
});
