const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {PluginManager}=require('../dist/main/plugins/PluginManager'),{validatePluginCard}=require('../dist/main/plugins/PluginPresentation'),{SessionManager}=require('../dist/main/session/SessionManager');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'iexa-plugin-test-'));t.after(()=>{assert.ok(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep+'iexa-plugin-test-'));fs.rmSync(root,{recursive:true,force:true});});const manager=new PluginManager(root);return{root,manager};}
function source(root,manifest,code){const dir=path.join(root,'source-'+Math.random().toString(36).slice(2));fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,'iexa-plugin.json'),JSON.stringify(manifest));fs.writeFileSync(path.join(dir,'index.cjs'),code||'module.exports.tools={run:()=>({output:"ok",success:true})}');fs.writeFileSync(path.join(dir,'ui.html'),'<!doctype html><title>panel</title>');return dir;}
const base={id:'test-plugin',name:'Test Plugin',description:'test',version:'1.0.0',main:'index.cjs',tools:[{name:'run',description:'run',parameters:{text:{type:'string'},count:{type:'integer'},enabled:{type:'boolean'}},required:['text']}]};
test('visual manifest supports v1 unchanged and validates v2 panel contributions and bounds',t=>{
 const {root,manager:m}=fixture(t);const legacy=m.install(source(root,{...base,ui:'ui.html'}));assert.equal(legacy.apiVersion,1);assert.equal(legacy.hasUI,true);m.remove(legacy.id);
 const v2={...base,apiVersion:2,contributions:{panels:[{id:'overview',title:'Overview',entry:'ui.html'}]}};const p=m.install(source(root,v2));assert.equal(p.contributions.panels.length,1);assert.equal(m.resolveUiAsset(p.id,'','overview').html,true);assert.throws(()=>m.resolveUiAsset(p.id,'../index.cjs','overview'),/超出/);assert.throws(()=>m.resolveUiAsset(p.id,'','missing'));m.setEnabled(p.id,false);assert.throws(()=>m.resolveUiAsset(p.id,'','overview'),/停用/);
 for(const manifest of [{...v2,apiVersion:3},{...v2,apiVersion:1},{...v2,contributions:{panels:[...v2.contributions.panels,...v2.contributions.panels]}},{...v2,contributions:{panels:[{id:'bad',title:'bad',entry:'../outside.html'}]}}])assert.throws(()=>new PluginManager(path.join(root,Math.random().toString(36).slice(2))).install(source(root,manifest)));
});
test('real child execution validates tool arguments and host-stamps bounded structured cards',async t=>{
 const {root,manager:m}=fixture(t);m.install(source(root,base,`module.exports.tools={run:(a)=>({output:a.text,success:true,pluginUI:{pluginId:'spoof'},ui:{version:1,title:'Snapshot',fields:[{label:'Text',value:a.text}],table:{columns:['Count'],rows:[[String(a.count)]]}}})}`));
 const result=await m.invoke(base.id,'run',{text:'hello',count:2,enabled:false});assert.equal(result.success,true,result.output);assert.equal(result.pluginUI.pluginId,base.id);assert.equal(result.pluginUI.card.fields[0].value,'hello');assert.equal(result.ui,undefined);
 for(const args of [{},{text:1},{text:'a',count:2.5},{text:'a',enabled:'yes'},{text:'a',unknown:true}])await assert.rejects(m.invoke(base.id,'run',args));
 const sessions=new SessionManager(path.join(root,'sessions'));await sessions.save('session',{toolCalls:[{id:'tool',name:'run',result}]});assert.deepEqual(new SessionManager(path.join(root,'sessions')).loadSync('session').toolCalls[0].result.pluginUI,result.pluginUI);
});
test('invalid visual output degrades to raw text, preserves tool success, and discards spoofed identity',async t=>{
 const {root,manager:m}=fixture(t);m.install(source(root,base,`module.exports.tools={run:()=>({output:'keep raw',success:true,pluginUI:{pluginId:'spoof'},ui:{version:9,title:'invalid'}})}`));const result=await m.invoke(base.id,'run',{text:'x'});assert.equal(result.success,true);assert.equal(result.output,'keep raw');assert.equal(result.pluginUI,undefined);assert.match(result.metadata.pluginUIError,/version/);
 assert.throws(()=>validatePluginCard({version:1,title:'x',table:{columns:['x'],rows:[['a','b']]}}));assert.throws(()=>validatePluginCard({version:1,title:'x',fields:Array(25).fill({label:'x',value:'y'})}));
});
test('host UI state is atomic, revision-checked, size-bounded, and survives manager restart',t=>{
 const {root,manager:m}=fixture(t);m.install(source(root,base));assert.deepEqual(m.readUIState(base.id),{revision:0,value:null});assert.deepEqual(m.writeUIState(base.id,0,{limit:12}),{revision:1,value:{limit:12}});assert.throws(()=>m.writeUIState(base.id,0,{limit:99}),/冲突/);assert.throws(()=>m.writeUIState(base.id,1,'文'.repeat(24000)),/64 KB/);assert.deepEqual(new PluginManager(root).readUIState(base.id),{revision:1,value:{limit:12}});m.setEnabled(base.id,false);assert.throws(()=>m.readUIState(base.id));m.setEnabled(base.id,true);assert.equal(m.readUIState(base.id).revision,1);
});
test('cancel and disable settle a real child before returning; no delayed file side effect',async t=>{
 const {root,manager:m}=fixture(t);m.install(source(root,base,`module.exports.tools={run:async(a,c)=>{require('fs').writeFileSync(require('path').join(c.workspaceDir,'started'),'yes');await new Promise(r=>setTimeout(r,3000));require('fs').writeFileSync(require('path').join(c.workspaceDir,'late'),'bad');return 'late'}}`));
 for(const mode of ['signal','disable']){fs.rmSync(path.join(root,'started'),{force:true});const controller=new AbortController();const running=m.invoke(base.id,'run',{text:'x'},controller.signal);for(let i=0;i<100&&!fs.existsSync(path.join(root,'started'));i++)await new Promise(r=>setTimeout(r,15));assert.ok(fs.existsSync(path.join(root,'started')));if(mode==='signal')controller.abort();else m.setEnabled(base.id,false);const result=await running;assert.equal(result.cancelled,true);assert.equal(result.success,false);assert.equal(fs.existsSync(path.join(root,'late')),false);m.setEnabled(base.id,true);}
});
test('workspace-pulse example executes on actual workspace contents and v2 panel resolves',async t=>{
 const {root,manager:m}=fixture(t);fs.writeFileSync(path.join(root,'fixture.txt'),'real bytes');const plugin=m.install(path.resolve('examples/plugins/workspace-pulse'));const result=await m.invoke(plugin.id,'inspect',{limit:50});assert.equal(result.success,true);assert.ok(result.pluginUI.card.table.rows.some(row=>row[0]==='fixture.txt'&&row[2]==='10 B'));assert.equal(m.resolveUiAsset(plugin.id,'panel.js','overview').html,false);
});
test('asset grants authorize only declared static roots, expire/revoke, and are separate from tool authority',t=>{
 const {root,manager:m}=fixture(t);m.install(source(root,{...base,apiVersion:2,contributions:{panels:[{id:'one',title:'One',entry:'ui.html'}]}}));const grant=m.createUIGrant(base.id,'one');assert.match(grant.url,/^\/plugin-assets\/[a-f0-9]{48}\/$/);assert.equal(m.resolveGrantedAsset(grant.token,'').html,true);assert.equal(m.resolveGrantedAsset(grant.token,'_iexa-sdk.js').sdk,true);assert.throws(()=>m.resolveGrantedAsset(grant.token,'../secret.txt'));assert.throws(()=>m.resolveGrantedAsset(grant.token,'index.cjs'));m.revokeUIGrant('other-plugin',grant.token);assert.equal(m.resolveGrantedAsset(grant.token,'').html,true);m.revokeUIGrant(base.id,grant.token);assert.throws(()=>m.resolveGrantedAsset(grant.token,''));const second=m.createUIGrant(base.id,'one');m.setEnabled(base.id,false);assert.throws(()=>m.resolveGrantedAsset(second.token,''));m.setEnabled(base.id,true);assert.throws(()=>m.resolveGrantedAsset(second.token,''));
});
