const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),ts=require('typescript');const {execFileSync}=require('node:child_process');
const {TranscriptRecorder}=require('../dist/main/session/TranscriptRecorder');const {StreamBatcher}=require('../dist/main/api/StreamBatcher');const {SessionManager}=require('../dist/main/session/SessionManager');const {create,flatten,root}=require('./helpers/transcript-harness.cjs');
function scenario(recorder){recorder.recordText('先检查。');recorder.recordThinking('分析A');recorder.recordThinking('继续A');recorder.recordTool('a','file_read');recorder.recordText('先检查。已读取。');recorder.recordThinking('分析B');recorder.recordTool('b','file_write');recorder.recordText('先检查。已读取。完成。');recorder.finish('completed');return {role:'assistant',content:'先检查。已读取。完成。',thinking:'分析A继续A分析B',thinkingLevel:'medium',toolCalls:[{id:'a',name:'file_read',args:{path:'a.ts'},result:{success:true,output:'read'}},{id:'b',name:'file_write',args:{path:'b.ts'},result:{success:true,output:'written'}}],transcript:recorder.snapshot()};}
const expected=[['text','先检查。'],['thinking','分析A继续A'],['tool','a'],['text','已读取。'],['thinking','分析B'],['tool','b'],['text','完成。']];

test('recorder assigns stable ordered IDs and contiguous ranges without duplicating adjacent deltas',()=>{
 let now=1000;const r=new TranscriptRecorder(()=>now+=100);const m=scenario(r);assert.deepEqual(m.transcript.items.map(x=>x.type),expected.map(x=>x[0]));assert.equal(new Set(m.transcript.items.map(x=>x.id)).size,7);assert.deepEqual(m.transcript.items.map(x=>x.sequence),[1,2,3,4,5,6,7]);assert.ok(m.transcript.items[1].durationMs>0);const before=r.snapshot();r.recordText('late');r.recordTool('c','shell_execute');assert.deepEqual(r.snapshot(),before);before.items[0].end=999;assert.notEqual(r.snapshot().items[0].end,999);
});
test('actual renderer produces interleaved text, reasoning and tools without repeated cumulative text',t=>{
 const {w,message}=create(t);w.handleTextDelta('先检查。');w.handleThinkingDelta('分析A');w.handleThinkingDelta('继续A');w.handleToolStart('a','file_read');w.handleToolComplete('a','file_read',{path:'a.ts'});w.handleTextDelta('先检查。已读取。');w.handleThinkingDelta('分析B');w.handleToolStart('b','file_write');w.handleToolComplete('b','file_write',{path:'b.ts'});w.handleTextDelta('先检查。已读取。完成。');assert.deepEqual(flatten(message),expected);assert.equal(message.querySelectorAll('.thinking-block').length,2);assert.equal(message._assistantText,'先检查。已读取。完成。');
});
test('server and renderer batching preserve boundaries even within one flush window',t=>{
 const {w,message}=create(t);const b=new StreamBatcher((event,data)=>{if(['text','thinking','tool_input'].includes(event))w.queueStreamUpdate(event,data,1);else {w.flushStreamUpdates('s');if(event==='tool_start')w.handleToolStart(data.id,data.name);}},60000);
 b.emit('text',{content:'A'});b.emit('thinking',{content:'R1'});b.emit('thinking',{content:'R2'});b.emit('tool_start',{id:'a',name:'file_read'});b.emit('text',{content:'AB'});b.emit('thinking',{content:'R3'});b.emit('text',{content:'ABC'});b.flush();w.flushStreamUpdates('s');assert.deepEqual(flatten(message),[['text','A'],['thinking','R1R2'],['tool','a'],['text','B'],['thinking','R3'],['text','C']]);
});
test('history projection restores recorded order and keeps existing tool result DOM',t=>{
 const {w,message}=create(t);const m=scenario(new TranscriptRecorder());message.querySelector('.message-content').textContent=m.content;for(const c of m.toolCalls){w.handleToolStart(c.id,c.name);w.handleToolComplete(c.id,c.name,c.args);}const row=w.currentToolBlocks.a.block;row.querySelector('.tool-result').textContent='read';assert.equal(w.restoreTranscriptOrder(message,m),true);assert.deepEqual(flatten(message),expected);assert.equal(message.querySelector('[data-tool-id="a"]'),row);assert.equal(row.querySelector('.tool-result').textContent,'read');assert.equal(message.dataset.transcriptState,'ordered');
});
test('legacy or corrupt history never receives guessed ordering or loses content',t=>{
 const {w,message}=create(t);message.querySelector('.message-content').textContent='legacy';assert.equal(w.restoreTranscriptOrder(message,{content:'legacy'}),false);assert.equal(message.dataset.transcriptState,'legacy');const m=scenario(new TranscriptRecorder());m.transcript.items[0].end=999;assert.equal(w.restoreTranscriptOrder(message,m),false);assert.match(message.textContent,/legacy/);assert.equal(message.dataset.transcriptState,'invalid');
});
test('terminal save uses actual server function and survives a fresh reader process',async t=>{
 const temp=await fsp.mkdtemp(path.join(os.tmpdir(),'iexa-events-'));t.after(()=>fsp.rm(temp,{recursive:true,force:true}));const store=new SessionManager(temp);const server=fs.readFileSync(path.join(root,'src/main/server.ts'),'utf8');const tree=ts.createSourceFile('server.ts',server,ts.ScriptTarget.Latest,true);const fn=tree.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='saveSessionMessages');const context={saveMessages:(id,messages)=>store.save(id,messages),agentCache:new Map(),saveSessionContext:()=>{},loadSessionStore:()=>({sessions:[]}),saveSessionStore:()=>{},normalizeThinkingLevel:x=>x,getThinkingLevel:()=> 'medium'};vm.runInNewContext(ts.transpileModule(fn.getText(tree),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);
 const m=scenario(new TranscriptRecorder());await context.saveSessionMessages('s',[],{role:'user',content:'run',timestamp:1},m.content,m.toolCalls,undefined,m.thinking,'medium',m.transcript);
 const saved=JSON.parse(execFileSync(process.execPath,['-e','const {SessionManager}=require(process.argv[1]);console.log(JSON.stringify(new SessionManager(process.argv[2]).loadSync("s")))',path.join(root,'dist/main/session/SessionManager.js'),temp],{encoding:'utf8',windowsHide:true}));assert.deepEqual(saved[1].transcript,m.transcript);assert.equal(saved[1].content,m.content);assert.equal(saved[1].toolCalls[1].result.output,'written');
});
test('cancelled and failed transcripts retain partial order, with no synthetic success',()=>{
 for(const state of ['failed','cancelled']){const r=new TranscriptRecorder();r.recordThinking('partial');r.recordTool('a','shell_execute');r.recordTool('a','shell_execute');r.finish(state);assert.equal(r.snapshot().status,state);assert.equal(r.snapshot().items.length,2);assert.equal(r.snapshot().items[1].type,'tool');}
});
test('text replacement or event cap marks history unsuitable for ordered projection instead of corrupting ranges silently',()=>{
 const r=new TranscriptRecorder();r.recordText('hello');r.recordText('changed');assert.equal(r.snapshot().valid,false);assert.equal(r.snapshot().invalidReason,'text_replaced');const limited=new TranscriptRecorder(Date.now,1);limited.recordText('a');limited.recordThinking('b');assert.equal(limited.snapshot().invalidReason,'event_limit');
});
